- .github/workflows/scans.yml
this upgrade to the new "nested matrix" format
> fix: upgrade scan workflow

- lighthouserc.json
only one report can be processed at the moment
> fix(lighthouse): reduce numberOfRuns

- dashlord.yml
Suite à un échange avec Olivier Szendy, nous ajoutons Osmose au Dashlord ^^
> Ajoute Osmose de la Dinum

- .github/workflows/report.yml
- .github/workflows/scans.yml
This updates the compiled report in the main branch on each new report generation
This also fix empty `author_name`, `author_email`
> fix: store report.json

- dashlord.yml
> Add ANAIS (fabnumdef)

- .github/workflows/report.yml
- .github/workflows/scans.yml
- utilisation des actions du monorepo
- ajout du screenshot
> fix: actions monorepo

- dashlord.yml
> branch monstagedetroisieme.fr, check for PR now

- .github/workflows/scans.yml
- dashlord.yml
Upgrade to new format so we can enable/disable tool for each url
> chore: upgrade job matrix

- .github/workflows/scans.yml
> fix(scans): fix schedule

- dashlord.yml
Pointe directement vers /login pour éviter les redirections.
> Ajout de l'app covoiturage

- .github/workflows/report.yml
> fix: update report.public-url

- .github/workflows/scans.yml
JavaScript treemap included in the detailed report : https://sia.codes/posts/lighthouse-treemap/
> fix: use lighthouse@8

- dashlord.yml
From https://github.com/SocialGouv/dashlord/issues/37 and https://github.com/SocialGouv/dashlord/issues/38
> feat: add disinfo + opentermsarchive

- dashlord.yml
from https://github.com/SocialGouv/dashlord/issues/39
> feat: ajout open-collectivites.fr

- dashlord.yml
_réseau social des professionnels de l’inclusion_
> Ajout d'une startup : communaute.inclusion (ITOU)

- dashlord.yml
Pour les voir ensemble sur https://dashlord.incubateur.net/#/tag/itou
> Ajout de tags pour les startups ITOU

- .github/workflows/report.yml
- .github/workflows/scans.yml
- dashlord.yml
Ajout d'un nouveau scan développé par @revolunet 🎉
> feat: add declaration-a11y to scans

- dashlord.yml
for an upcoming breaking change in dashlord-actions/report
> chore: add config.marianne

- dashlord.yml
New address is mon-entreprise.urssaf.fr.
> Change mon-entreprise url

- .github/workflows/report.yml
- dashlord.yml
Add matomo tracker for new dashlord report version
> feat: add matomo

- .github/workflows/scans.yml
Merci au MTES et à @tristanrobert ! ;)
> Ajoute un check des pages stats

- .github/workflows/scans.yml
- README.md
- docs/stats.md
> Revert "add use of check-url-action"

- dashlord.yml
> Suppression volontaires.fonction-publique.gouv.fr

- dashlord.yml
- suppression des / finaux superflus
- désactivation détection de la declaration a11y hors du frontend
- désactivation des stats hors du frontend
- ajout de tags 'api'
- ajout de titres
> Mise à jour DORA

- dashlord.yml
> Ajout de Métiers Numériques

- dashlord.yml
> fix(config): fix audioconf betaId

- dashlord.yml
API Entreprise souhaiterai être référencé sur dashblord est-ce possible ? La PR est-elle correcte ?
> Add api entreprise

- dashlord.yml
Améliorations en cours au niveau de l'accessibilité / page budget & stats.
> Changement d'URL produit Usine à Chatbots

- dashlord.yml
Bonjour,
Voici la PR pour  l'ajout du frontal SPPNaut dans dashlord. 
Merci !
> Ajout SPPNaut

- dashlord.yml
Ajout startup Pôle emploi mobiville
> Ajout mobiville

- .github/workflows/scans.yml
Fais un retry du scan mozilla si le 1er a échoué
> chore(scan): add mozilla retry

- dashlord.yml
Hello, on souhaite ajouter le Tableau de bord de l'apprentissage au Dashlord. 
Merci d'avance :)
> Ajout du Tableau de bord Apprentissage

- dashlord.yml
> fix: add https://conseil-refondation.fr

- dashlord.yml
https://github.com/betagouv/dashlord/issues/91
> change url for ma-cantine

- dashlord.yml
Cette PR ajoute la plateforme impact.
Je ne sais pas où trouver la valeur de `betaId` donc j'ai mis la valeur qui me semblait la plus logique (`impact`).
> Ajout du service impact

- dashlord.yml
Cette PR ajoute la startup d'état Dotations Locales.
> Ajout de la startup Dotations Locales

- dashlord.yml
The url of the project is wrong
> update immersion facilitee url

- dashlord.yml
closes https://github.com/betagouv/api-subventions-asso/issues/531
> Update dashlord.yml - add data-subvention

- dashlord.yml
> remove matcha service

- dashlord.yml
Estime reprise d'emploi est intégré au site candidat de Pôle emploi.
> Update estime url

- dashlord.yml
> Add eimis SE

- dashlord.yml
Le service utilise le nom de domaine adapté.
> Renommage de la plateforme Impact en Portail-rse

- .github/workflows/scans.yml
- dashlord.yml
- modifications des categories pour faire apparaitre l'incubateur
- suppression des `alumni`
- ajout tests ecoindex et DSFR
> chore: Cleanup config

- .github/workflows/report.yml
- .github/workflows/scans.yml
- dashlord.yml
- disable nuclei scan
- disable "fetch" in [commit action](https://github.com/EndBug/add-and-commit/)
> chore: perf optims

- dashlord.yml
Bonjour,
Voici une PR pour ajouter [Sirius](https://sirius.apprentissage.beta.gouv.fr/) à Dashlord.
Julien, je me suis permis de te mettre en reviewer en voyant que tu avais mergé les PR précédentes, n'hésite pas à me le signaler si ça n'est pas la procédure!
Merci,
> Add Sirius

- dashlord.yml
Bonjour,
Je souhaite ajouter ROMIN sur DashLord. L'URL sera amenée à être modifiée.
J'ai repris la catégorie des autres SE du MJ.
@revolunet Julien, je me permets de t'ajouter en reviewer.
Merci,
> Ajout de la SE ROMIN (MJ)

- dashlord.yml
> Add Pass Sport

- dashlord.yml
Ajout URL de la startup Maestro
> Update dashlord.yml - add Maestro

- dashlord.yml
> chore: add assistant-declaration environments

- dashlord.yml
We will update this entry with the production description once it has been deployed!
> Add QualiCharge API (staging)
